/**
 * Regenerates worker/fonts.ts: the two site typefaces, subset to the
 * characters a README card can contain and inlined as base64.
 *
 *   node scripts/subset-fonts.ts
 *
 * A card is loaded through an <img>, where a remote font URL is not allowed to
 * load — a data URI is not a fetch, so it is. Google Fonts will cut a face
 * down to an exact character set, which is what keeps the two faces to ~15 KB
 * between them instead of ~200 KB.
 *
 * Run this by hand when CHARACTERS changes, not on every build: a deploy
 * should never depend on fonts.googleapis.com being reachable.
 */
import { writeFile } from "node:fs/promises";

/** Google Fonts serves woff2 only to clients that claim to support it. */
const UA = "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36";

const OUTPUT = new URL("../worker/fonts.ts", import.meta.url);

/**
 * Everything a card can print. The mono face carries the labels, the handle
 * and the display name, so it needs latin plus the punctuation GitHub allows
 * in a login and the ellipsis a clamped name ends in; the display face only
 * ever sets the two numbers.
 */
const CHARACTERS = {
  mono: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ,.-–—·…@#/:'’()+",
  display: "0123456789,+",
};

const FACES = [
  {
    name: "display",
    family: "Bricolage+Grotesque:opsz,wght@12..96,800",
    characters: CHARACTERS.display,
  },
  { name: "mono", family: "DM+Mono:wght@400", characters: CHARACTERS.mono },
] as const;

async function subset(family: string, characters: string): Promise<string> {
  const query = `family=${family}&text=${encodeURIComponent(characters)}`;
  const css = await fetch(`https://fonts.googleapis.com/css2?${query}`, {
    headers: { "User-Agent": UA },
  });
  if (!css.ok) throw new Error(`Google Fonts refused ${family} (${css.status})`);

  const url = /https:\/\/fonts\.gstatic\.com\/[^)]*/.exec(await css.text())?.[0];
  if (!url) throw new Error(`No woff2 in the Google Fonts response for ${family}`);

  const font = await fetch(url);
  if (!font.ok) throw new Error(`Could not fetch the subset for ${family} (${font.status})`);
  return Buffer.from(await font.arrayBuffer()).toString("base64");
}

const payloads = await Promise.all(FACES.map((face) => subset(face.family, face.characters)));

const lines = [
  "/*",
  " * Generated by scripts/subset-fonts.ts — do not edit by hand.",
  " *",
  " * Bricolage Grotesque and DM Mono, subset to the characters a card can",
  " * print and base64-encoded for inlining into the SVG. Both faces are",
  " * licensed under the SIL Open Font License 1.1; the licences are in",
  " * worker/fonts/.",
  " */",
  "",
  "export interface CardFontData {",
  "  display: string;",
  "  mono: string;",
  "}",
  "",
  "export const CARD_FONTS: CardFontData = {",
  ...FACES.map((face, index) => `  ${face.name}: "${payloads[index]}",`),
  "};",
  "",
];

await writeFile(OUTPUT, lines.join("\n"));

for (const [index, face] of FACES.entries()) {
  const kb = ((payloads[index].length * 3) / 4 / 1024).toFixed(1);
  console.log(`${face.name}: ${kb} KB (${[...new Set(face.characters)].length} characters)`);
}
